---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: param-and-results
spec:
  params:
    - name: git_url
      type: string
    - name: git_revision
      type: string
  tasks:
    - name: task-01
      taskRef:
        name: task-01
      # Step 1: Pass the "git_url" and "git_revision" parameters to the task
      params:
        - name: git_url
          value: $(params.git_url)
        - name: git_revision
          value: $(params.git_revision)

    - name: task-02
      runAfter:
        - task-01
      taskRef:
        name: task-02
      # Step 2: Pass the "git_commit" result from task-01 to task-02
      params:
        - name: git_commit
          value: $(tasks.task-01.results.git_commit)
